### ISSUE TITLE
Igra se glavi

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG012-guitar-hero#2]
Po pokretanju igre, kad se pritisne neki od tastera, igra se samo zaglavi

**Comment by greenera** [comment]
Nadjeni uzroci glavljenja igre po pritisku tastera tastature i nacin popravke:

- Na nekim sistemima nije bilo uspesno uhvaceno enter dugme sa key == 13, sto je popravljeno dodavanjem key == '\n' u proveru

- U modu za dva igraca tastatura nije uopste reagovala, sto je popravljeno time sto je dodato podesavanje parametra brIgraca = 2

- U igri tastatura nije reagovala na velika slova, sto je popravljeno ukljucenjem provere pritisnutih tastera velikih slova

- Pri samom pokretanju sa './gh' igra nije reagovala ni na jedan tastaer oko 3 sekunde, sto je popravljeno preusmeravanjem pauze na glavni prozor i brisanjem dodatnog prozora
